// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[slug].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/seed-users.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/login.tsx";
import * as $6 from "./routes/logout.ts";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Editor.tsx";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/seed-users.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/login.tsx": $5,
    "./routes/logout.ts": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Editor.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
